package com.boluclac.blog.database.entities;
// Generated Nov 8, 2018, 12:11:55 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MstLanguage generated by hbm2java
 */
@Entity
@Table(name = "mst_language", catalog = "boluclac_blog", uniqueConstraints = @UniqueConstraint(columnNames = "value"))
public class MstLanguage implements java.io.Serializable {

    private int     id;

    private int     version;

    private MstUser mstUserByCreater;

    private MstUser mstUserByUpdater;

    private String  value;

    private String  text;

    private boolean delFlag;

    private String  createDate;

    private String  updateDate;

    public MstLanguage() {

    }

    public MstLanguage(int id, MstUser mstUserByCreater, MstUser mstUserByUpdater, String value, String text, boolean delFlag,
            String createDate, String updateDate) {

        this.id = id;
        this.mstUserByCreater = mstUserByCreater;
        this.mstUserByUpdater = mstUserByUpdater;
        this.value = value;
        this.text = text;
        this.delFlag = delFlag;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {

        return this.id;
    }

    public void setId(int id) {

        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {

        return this.version;
    }

    public void setVersion(int version) {

        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "creater", nullable = false)
    public MstUser getMstUserByCreater() {

        return this.mstUserByCreater;
    }

    public void setMstUserByCreater(MstUser mstUserByCreater) {

        this.mstUserByCreater = mstUserByCreater;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updater", nullable = false)
    public MstUser getMstUserByUpdater() {

        return this.mstUserByUpdater;
    }

    public void setMstUserByUpdater(MstUser mstUserByUpdater) {

        this.mstUserByUpdater = mstUserByUpdater;
    }

    @Column(name = "value", unique = true, nullable = false, length = 16)
    public String getValue() {

        return this.value;
    }

    public void setValue(String value) {

        this.value = value;
    }

    @Column(name = "text", nullable = false, length = 64)
    public String getText() {

        return this.text;
    }

    public void setText(String text) {

        this.text = text;
    }

    @Column(name = "del_flag", nullable = false)
    public boolean isDelFlag() {

        return this.delFlag;
    }

    public void setDelFlag(boolean delFlag) {

        this.delFlag = delFlag;
    }

    @Column(name = "create_date", nullable = false, length = 14)
    public String getCreateDate() {

        return this.createDate;
    }

    public void setCreateDate(String createDate) {

        this.createDate = createDate;
    }

    @Column(name = "update_date", nullable = false, length = 14)
    public String getUpdateDate() {

        return this.updateDate;
    }

    public void setUpdateDate(String updateDate) {

        this.updateDate = updateDate;
    }

}
