package com.boluclac.blog.database.entities;
// Generated Nov 6, 2018, 10:01:22 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MstRole generated by hbm2java
 */
@Entity
@Table(name = "mst_role", catalog = "boluclac_blog", uniqueConstraints = @UniqueConstraint(columnNames = "value"))
public class MstRole implements java.io.Serializable {

    private int                  id;

    private int                  version;

    private MstUser              mstUserByUpdater;

    private MstUser              mstUserByCreater;

    private String               value;

    private String               name;

    private boolean              system;

    private boolean              delFlag;

    private String               createDate;

    private String               updateDate;

    private Set<LnkUserRole>     lnkUserRoles     = new HashSet<LnkUserRole>(0);

    private Set<LinkApiLinkRole> linkApiLinkRoles = new HashSet<LinkApiLinkRole>(0);

    public MstRole() {

    }

    public MstRole(int id, MstUser mstUserByUpdater, MstUser mstUserByCreater, String value, String name, boolean system, boolean delFlag,
            String createDate, String updateDate) {

        this.id = id;
        this.mstUserByUpdater = mstUserByUpdater;
        this.mstUserByCreater = mstUserByCreater;
        this.value = value;
        this.name = name;
        this.system = system;
        this.delFlag = delFlag;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public MstRole(int id, MstUser mstUserByUpdater, MstUser mstUserByCreater, String value, String name, boolean system, boolean delFlag,
            String createDate, String updateDate, Set<LnkUserRole> lnkUserRoles, Set<LinkApiLinkRole> linkApiLinkRoles) {

        this.id = id;
        this.mstUserByUpdater = mstUserByUpdater;
        this.mstUserByCreater = mstUserByCreater;
        this.value = value;
        this.name = name;
        this.system = system;
        this.delFlag = delFlag;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.lnkUserRoles = lnkUserRoles;
        this.linkApiLinkRoles = linkApiLinkRoles;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {

        return this.id;
    }

    public void setId(int id) {

        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {

        return this.version;
    }

    public void setVersion(int version) {

        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updater", nullable = false)
    public MstUser getMstUserByUpdater() {

        return this.mstUserByUpdater;
    }

    public void setMstUserByUpdater(MstUser mstUserByUpdater) {

        this.mstUserByUpdater = mstUserByUpdater;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "creater", nullable = false)
    public MstUser getMstUserByCreater() {

        return this.mstUserByCreater;
    }

    public void setMstUserByCreater(MstUser mstUserByCreater) {

        this.mstUserByCreater = mstUserByCreater;
    }

    @Column(name = "value", unique = true, nullable = false, length = 50)
    public String getValue() {

        return this.value;
    }

    public void setValue(String value) {

        this.value = value;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {

        return this.name;
    }

    public void setName(String name) {

        this.name = name;
    }

    @Column(name = "system", nullable = false)
    public boolean isSystem() {

        return this.system;
    }

    public void setSystem(boolean system) {

        this.system = system;
    }

    @Column(name = "del_flag", nullable = false)
    public boolean isDelFlag() {

        return this.delFlag;
    }

    public void setDelFlag(boolean delFlag) {

        this.delFlag = delFlag;
    }

    @Column(name = "create_date", nullable = false, length = 14)
    public String getCreateDate() {

        return this.createDate;
    }

    public void setCreateDate(String createDate) {

        this.createDate = createDate;
    }

    @Column(name = "update_date", nullable = false, length = 14)
    public String getUpdateDate() {

        return this.updateDate;
    }

    public void setUpdateDate(String updateDate) {

        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mstRole")
    public Set<LnkUserRole> getLnkUserRoles() {

        return this.lnkUserRoles;
    }

    public void setLnkUserRoles(Set<LnkUserRole> lnkUserRoles) {

        this.lnkUserRoles = lnkUserRoles;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mstRole")
    public Set<LinkApiLinkRole> getLinkApiLinkRoles() {

        return this.linkApiLinkRoles;
    }

    public void setLinkApiLinkRoles(Set<LinkApiLinkRole> linkApiLinkRoles) {

        this.linkApiLinkRoles = linkApiLinkRoles;
    }

}
