package com.boluclac.blog.database.entities;
// Generated Nov 6, 2018, 10:01:22 PM by Hibernate Tools 5.2.11.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OauthCodeId generated by hbm2java
 */
@Embeddable
public class OauthCodeId implements java.io.Serializable {

    private String code;

    private byte[] authentication;

    public OauthCodeId() {

    }

    public OauthCodeId(String code, byte[] authentication) {

        this.code = code;
        this.authentication = authentication;
    }

    @Column(name = "code")
    public String getCode() {

        return this.code;
    }

    public void setCode(String code) {

        this.code = code;
    }

    @Column(name = "authentication")
    public byte[] getAuthentication() {

        return this.authentication;
    }

    public void setAuthentication(byte[] authentication) {

        this.authentication = authentication;
    }

    public boolean equals(Object other) {

        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof OauthCodeId))
            return false;
        OauthCodeId castOther = (OauthCodeId) other;

        return ((this.getCode() == castOther.getCode())
                || (this.getCode() != null && castOther.getCode() != null && this.getCode().equals(castOther.getCode())))
                && ((this.getAuthentication() == castOther.getAuthentication())
                        || (this.getAuthentication() != null && castOther.getAuthentication() != null
                                && Arrays.equals(this.getAuthentication(), castOther.getAuthentication())));
    }

    public int hashCode() {

        int result = 17;

        result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
        result = 37 * result + (getAuthentication() == null ? 0 : Arrays.hashCode(this.getAuthentication()));
        return result;
    }

}
