package com.boluclac.blog.database.repositories.base;

import com.boluclac.blog.database.entities.Clientdetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 06/11/2018
*/
@Repository
public interface ClientdetailsBaseRepository extends JpaRepository<Clientdetails, String>, JpaSpecificationExecutor<Clientdetails> {

}
