package com.boluclac.blog.database.repositories.base;

import com.boluclac.blog.database.entities.Language;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 27/10/2018
*/
@Repository
public interface LanguageBaseRepository extends JpaRepository<Language, Integer>, JpaSpecificationExecutor<Language> {

}
