package com.boluclac.blog.database.repositories.base;

import com.boluclac.blog.database.entities.Languages;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 25/10/2018
*/
@Repository
public interface LanguagesBaseRepository extends JpaRepository<Languages, Integer>, JpaSpecificationExecutor<Languages>, QuerydslPredicateExecutor<Languages> {

}
