package com.boluclac.blog.database.entities;
// Generated Oct 25, 2018, 9:44:19 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Languages generated by hbm2java
 */
@Entity
@Table(name = "languages", catalog = "boluclac_blog")
public class Languages implements java.io.Serializable {

    private int    id;

    private int    version;

    private String value;

    private String text;

    private int    creater;

    private int    updater;

    private String createDate;

    private String updateDate;

    public Languages() {

    }

    public Languages(int id, String value, String text, int creater, int updater, String createDate, String updateDate) {

        this.id = id;
        this.value = value;
        this.text = text;
        this.creater = creater;
        this.updater = updater;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {

        return this.id;
    }

    public void setId(int id) {

        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {

        return this.version;
    }

    public void setVersion(int version) {

        this.version = version;
    }

    @Column(name = "value", nullable = false, length = 16)
    public String getValue() {

        return this.value;
    }

    public void setValue(String value) {

        this.value = value;
    }

    @Column(name = "text", nullable = false, length = 64)
    public String getText() {

        return this.text;
    }

    public void setText(String text) {

        this.text = text;
    }

    @Column(name = "creater", nullable = false)
    public int getCreater() {

        return this.creater;
    }

    public void setCreater(int creater) {

        this.creater = creater;
    }

    @Column(name = "updater", nullable = false)
    public int getUpdater() {

        return this.updater;
    }

    public void setUpdater(int updater) {

        this.updater = updater;
    }

    @Column(name = "create_date", nullable = false, length = 14)
    public String getCreateDate() {

        return this.createDate;
    }

    public void setCreateDate(String createDate) {

        this.createDate = createDate;
    }

    @Column(name = "update_date", nullable = false, length = 14)
    public String getUpdateDate() {

        return this.updateDate;
    }

    public void setUpdateDate(String updateDate) {

        this.updateDate = updateDate;
    }

}
